// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: comments.proto

package comments

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CommentAddRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CommentAddRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentAddRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommentAddRequestMultiError, or nil if none found.
func (m *CommentAddRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentAddRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := CommentAddRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSku() <= 0 {
		err := CommentAddRequestValidationError{
			field:  "Sku",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetComment()); l < 1 || l > 255 {
		err := CommentAddRequestValidationError{
			field:  "Comment",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CommentAddRequestMultiError(errors)
	}

	return nil
}

// CommentAddRequestMultiError is an error wrapping multiple validation errors
// returned by CommentAddRequest.ValidateAll() if the designated constraints
// aren't met.
type CommentAddRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentAddRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentAddRequestMultiError) AllErrors() []error { return m }

// CommentAddRequestValidationError is the validation error returned by
// CommentAddRequest.Validate if the designated constraints aren't met.
type CommentAddRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentAddRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentAddRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentAddRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentAddRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentAddRequestValidationError) ErrorName() string {
	return "CommentAddRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CommentAddRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentAddRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentAddRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentAddRequestValidationError{}

// Validate checks the field values on CommentAddResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CommentAddResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentAddResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommentAddResponseMultiError, or nil if none found.
func (m *CommentAddResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentAddResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CommentAddResponseMultiError(errors)
	}

	return nil
}

// CommentAddResponseMultiError is an error wrapping multiple validation errors
// returned by CommentAddResponse.ValidateAll() if the designated constraints
// aren't met.
type CommentAddResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentAddResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentAddResponseMultiError) AllErrors() []error { return m }

// CommentAddResponseValidationError is the validation error returned by
// CommentAddResponse.Validate if the designated constraints aren't met.
type CommentAddResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentAddResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentAddResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentAddResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentAddResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentAddResponseValidationError) ErrorName() string {
	return "CommentAddResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CommentAddResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentAddResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentAddResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentAddResponseValidationError{}

// Validate checks the field values on CommentGetByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CommentGetByIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentGetByIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommentGetByIDRequestMultiError, or nil if none found.
func (m *CommentGetByIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentGetByIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := CommentGetByIDRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CommentGetByIDRequestMultiError(errors)
	}

	return nil
}

// CommentGetByIDRequestMultiError is an error wrapping multiple validation
// errors returned by CommentGetByIDRequest.ValidateAll() if the designated
// constraints aren't met.
type CommentGetByIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentGetByIDRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentGetByIDRequestMultiError) AllErrors() []error { return m }

// CommentGetByIDRequestValidationError is the validation error returned by
// CommentGetByIDRequest.Validate if the designated constraints aren't met.
type CommentGetByIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentGetByIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentGetByIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentGetByIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentGetByIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentGetByIDRequestValidationError) ErrorName() string {
	return "CommentGetByIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CommentGetByIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentGetByIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentGetByIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentGetByIDRequestValidationError{}

// Validate checks the field values on CommentGetByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CommentGetByIDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentGetByIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommentGetByIDResponseMultiError, or nil if none found.
func (m *CommentGetByIDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentGetByIDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Sku

	// no validation rules for Comment

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommentGetByIDResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommentGetByIDResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommentGetByIDResponseValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CommentGetByIDResponseMultiError(errors)
	}

	return nil
}

// CommentGetByIDResponseMultiError is an error wrapping multiple validation
// errors returned by CommentGetByIDResponse.ValidateAll() if the designated
// constraints aren't met.
type CommentGetByIDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentGetByIDResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentGetByIDResponseMultiError) AllErrors() []error { return m }

// CommentGetByIDResponseValidationError is the validation error returned by
// CommentGetByIDResponse.Validate if the designated constraints aren't met.
type CommentGetByIDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentGetByIDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentGetByIDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentGetByIDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentGetByIDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentGetByIDResponseValidationError) ErrorName() string {
	return "CommentGetByIDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CommentGetByIDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentGetByIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentGetByIDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentGetByIDResponseValidationError{}

// Validate checks the field values on CommentEditRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CommentEditRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentEditRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommentEditRequestMultiError, or nil if none found.
func (m *CommentEditRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentEditRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := CommentEditRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCommentId() <= 0 {
		err := CommentEditRequestValidationError{
			field:  "CommentId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetNewComment()); l < 1 || l > 255 {
		err := CommentEditRequestValidationError{
			field:  "NewComment",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CommentEditRequestMultiError(errors)
	}

	return nil
}

// CommentEditRequestMultiError is an error wrapping multiple validation errors
// returned by CommentEditRequest.ValidateAll() if the designated constraints
// aren't met.
type CommentEditRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentEditRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentEditRequestMultiError) AllErrors() []error { return m }

// CommentEditRequestValidationError is the validation error returned by
// CommentEditRequest.Validate if the designated constraints aren't met.
type CommentEditRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentEditRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentEditRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentEditRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentEditRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentEditRequestValidationError) ErrorName() string {
	return "CommentEditRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CommentEditRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentEditRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentEditRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentEditRequestValidationError{}

// Validate checks the field values on CommentEditResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CommentEditResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentEditResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommentEditResponseMultiError, or nil if none found.
func (m *CommentEditResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentEditResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CommentEditResponseMultiError(errors)
	}

	return nil
}

// CommentEditResponseMultiError is an error wrapping multiple validation
// errors returned by CommentEditResponse.ValidateAll() if the designated
// constraints aren't met.
type CommentEditResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentEditResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentEditResponseMultiError) AllErrors() []error { return m }

// CommentEditResponseValidationError is the validation error returned by
// CommentEditResponse.Validate if the designated constraints aren't met.
type CommentEditResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentEditResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentEditResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentEditResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentEditResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentEditResponseValidationError) ErrorName() string {
	return "CommentEditResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CommentEditResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentEditResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentEditResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentEditResponseValidationError{}

// Validate checks the field values on CommentListBySKURequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CommentListBySKURequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentListBySKURequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommentListBySKURequestMultiError, or nil if none found.
func (m *CommentListBySKURequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentListBySKURequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSku() <= 0 {
		err := CommentListBySKURequestValidationError{
			field:  "Sku",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCursor()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommentListBySKURequestValidationError{
					field:  "Cursor",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommentListBySKURequestValidationError{
					field:  "Cursor",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCursor()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommentListBySKURequestValidationError{
				field:  "Cursor",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CommentListBySKURequestMultiError(errors)
	}

	return nil
}

// CommentListBySKURequestMultiError is an error wrapping multiple validation
// errors returned by CommentListBySKURequest.ValidateAll() if the designated
// constraints aren't met.
type CommentListBySKURequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentListBySKURequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentListBySKURequestMultiError) AllErrors() []error { return m }

// CommentListBySKURequestValidationError is the validation error returned by
// CommentListBySKURequest.Validate if the designated constraints aren't met.
type CommentListBySKURequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentListBySKURequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentListBySKURequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentListBySKURequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentListBySKURequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentListBySKURequestValidationError) ErrorName() string {
	return "CommentListBySKURequestValidationError"
}

// Error satisfies the builtin error interface
func (e CommentListBySKURequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentListBySKURequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentListBySKURequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentListBySKURequestValidationError{}

// Validate checks the field values on CommentListBySKUResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CommentListBySKUResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentListBySKUResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommentListBySKUResponseMultiError, or nil if none found.
func (m *CommentListBySKUResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentListBySKUResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetComments() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CommentListBySKUResponseValidationError{
						field:  fmt.Sprintf("Comments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CommentListBySKUResponseValidationError{
						field:  fmt.Sprintf("Comments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CommentListBySKUResponseValidationError{
					field:  fmt.Sprintf("Comments[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetCursor()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommentListBySKUResponseValidationError{
					field:  "Cursor",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommentListBySKUResponseValidationError{
					field:  "Cursor",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCursor()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommentListBySKUResponseValidationError{
				field:  "Cursor",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CommentListBySKUResponseMultiError(errors)
	}

	return nil
}

// CommentListBySKUResponseMultiError is an error wrapping multiple validation
// errors returned by CommentListBySKUResponse.ValidateAll() if the designated
// constraints aren't met.
type CommentListBySKUResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentListBySKUResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentListBySKUResponseMultiError) AllErrors() []error { return m }

// CommentListBySKUResponseValidationError is the validation error returned by
// CommentListBySKUResponse.Validate if the designated constraints aren't met.
type CommentListBySKUResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentListBySKUResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentListBySKUResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentListBySKUResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentListBySKUResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentListBySKUResponseValidationError) ErrorName() string {
	return "CommentListBySKUResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CommentListBySKUResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentListBySKUResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentListBySKUResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentListBySKUResponseValidationError{}

// Validate checks the field values on Cursor with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Cursor) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Cursor with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CursorMultiError, or nil if none found.
func (m *Cursor) ValidateAll() error {
	return m.validate(true)
}

func (m *Cursor) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CursorMultiError(errors)
	}

	return nil
}

// CursorMultiError is an error wrapping multiple validation errors returned by
// Cursor.ValidateAll() if the designated constraints aren't met.
type CursorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CursorMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CursorMultiError) AllErrors() []error { return m }

// CursorValidationError is the validation error returned by Cursor.Validate if
// the designated constraints aren't met.
type CursorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CursorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CursorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CursorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CursorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CursorValidationError) ErrorName() string { return "CursorValidationError" }

// Error satisfies the builtin error interface
func (e CursorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCursor.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CursorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CursorValidationError{}

// Validate checks the field values on CommentBySku with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CommentBySku) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentBySku with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CommentBySkuMultiError, or
// nil if none found.
func (m *CommentBySku) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentBySku) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for Comment

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommentBySkuValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommentBySkuValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommentBySkuValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CommentBySkuMultiError(errors)
	}

	return nil
}

// CommentBySkuMultiError is an error wrapping multiple validation errors
// returned by CommentBySku.ValidateAll() if the designated constraints aren't met.
type CommentBySkuMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentBySkuMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentBySkuMultiError) AllErrors() []error { return m }

// CommentBySkuValidationError is the validation error returned by
// CommentBySku.Validate if the designated constraints aren't met.
type CommentBySkuValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentBySkuValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentBySkuValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentBySkuValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentBySkuValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentBySkuValidationError) ErrorName() string { return "CommentBySkuValidationError" }

// Error satisfies the builtin error interface
func (e CommentBySkuValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentBySku.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentBySkuValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentBySkuValidationError{}

// Validate checks the field values on CommentListByUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CommentListByUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentListByUserRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommentListByUserRequestMultiError, or nil if none found.
func (m *CommentListByUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentListByUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := CommentListByUserRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CommentListByUserRequestMultiError(errors)
	}

	return nil
}

// CommentListByUserRequestMultiError is an error wrapping multiple validation
// errors returned by CommentListByUserRequest.ValidateAll() if the designated
// constraints aren't met.
type CommentListByUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentListByUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentListByUserRequestMultiError) AllErrors() []error { return m }

// CommentListByUserRequestValidationError is the validation error returned by
// CommentListByUserRequest.Validate if the designated constraints aren't met.
type CommentListByUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentListByUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentListByUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentListByUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentListByUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentListByUserRequestValidationError) ErrorName() string {
	return "CommentListByUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CommentListByUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentListByUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentListByUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentListByUserRequestValidationError{}

// Validate checks the field values on CommentListByUserResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CommentListByUserResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentListByUserResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommentListByUserResponseMultiError, or nil if none found.
func (m *CommentListByUserResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentListByUserResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetComments() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CommentListByUserResponseValidationError{
						field:  fmt.Sprintf("Comments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CommentListByUserResponseValidationError{
						field:  fmt.Sprintf("Comments[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CommentListByUserResponseValidationError{
					field:  fmt.Sprintf("Comments[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CommentListByUserResponseMultiError(errors)
	}

	return nil
}

// CommentListByUserResponseMultiError is an error wrapping multiple validation
// errors returned by CommentListByUserResponse.ValidateAll() if the
// designated constraints aren't met.
type CommentListByUserResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentListByUserResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentListByUserResponseMultiError) AllErrors() []error { return m }

// CommentListByUserResponseValidationError is the validation error returned by
// CommentListByUserResponse.Validate if the designated constraints aren't met.
type CommentListByUserResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentListByUserResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentListByUserResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentListByUserResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentListByUserResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentListByUserResponseValidationError) ErrorName() string {
	return "CommentListByUserResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CommentListByUserResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentListByUserResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentListByUserResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentListByUserResponseValidationError{}

// Validate checks the field values on CommentByUserID with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CommentByUserID) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommentByUserID with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CommentByUserIDMultiError, or nil if none found.
func (m *CommentByUserID) ValidateAll() error {
	return m.validate(true)
}

func (m *CommentByUserID) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Sku

	// no validation rules for Comment

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CommentByUserIDValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CommentByUserIDValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CommentByUserIDValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CommentByUserIDMultiError(errors)
	}

	return nil
}

// CommentByUserIDMultiError is an error wrapping multiple validation errors
// returned by CommentByUserID.ValidateAll() if the designated constraints
// aren't met.
type CommentByUserIDMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommentByUserIDMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommentByUserIDMultiError) AllErrors() []error { return m }

// CommentByUserIDValidationError is the validation error returned by
// CommentByUserID.Validate if the designated constraints aren't met.
type CommentByUserIDValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentByUserIDValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentByUserIDValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentByUserIDValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentByUserIDValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentByUserIDValidationError) ErrorName() string { return "CommentByUserIDValidationError" }

// Error satisfies the builtin error interface
func (e CommentByUserIDValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentByUserID.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentByUserIDValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentByUserIDValidationError{}
