// Code generated by http://github.com/gojuno/minimock (v3.4.4). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/Sane4eck55/CART-LOMS-COMMENTS-NOTIFIER/cart/internal/domain/service.Loms -o loms_mock.go -n LomsMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	pbLoms "github.com/Sane4eck55/CART-LOMS-COMMENTS-NOTIFIER/cart/pkg/github.com/Sane4eck55/CART-LOMS-COMMENTS-NOTIFIER/loms/api/v1"
	"github.com/gojuno/minimock/v3"
)

// LomsMock implements mm_service.Loms
type LomsMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateOrder          func(ctx context.Context, req *pbLoms.OrderCreateRequest) (op1 *pbLoms.OrderCreateResponse, err error)
	funcCreateOrderOrigin    string
	inspectFuncCreateOrder   func(ctx context.Context, req *pbLoms.OrderCreateRequest)
	afterCreateOrderCounter  uint64
	beforeCreateOrderCounter uint64
	CreateOrderMock          mLomsMockCreateOrder

	funcGetStocksInfo          func(ctx context.Context, req *pbLoms.StocksInfoRequest) (sp1 *pbLoms.StocksInfoResponse, err error)
	funcGetStocksInfoOrigin    string
	inspectFuncGetStocksInfo   func(ctx context.Context, req *pbLoms.StocksInfoRequest)
	afterGetStocksInfoCounter  uint64
	beforeGetStocksInfoCounter uint64
	GetStocksInfoMock          mLomsMockGetStocksInfo
}

// NewLomsMock returns a mock for mm_service.Loms
func NewLomsMock(t minimock.Tester) *LomsMock {
	m := &LomsMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateOrderMock = mLomsMockCreateOrder{mock: m}
	m.CreateOrderMock.callArgs = []*LomsMockCreateOrderParams{}

	m.GetStocksInfoMock = mLomsMockGetStocksInfo{mock: m}
	m.GetStocksInfoMock.callArgs = []*LomsMockGetStocksInfoParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLomsMockCreateOrder struct {
	optional           bool
	mock               *LomsMock
	defaultExpectation *LomsMockCreateOrderExpectation
	expectations       []*LomsMockCreateOrderExpectation

	callArgs []*LomsMockCreateOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsMockCreateOrderExpectation specifies expectation struct of the Loms.CreateOrder
type LomsMockCreateOrderExpectation struct {
	mock               *LomsMock
	params             *LomsMockCreateOrderParams
	paramPtrs          *LomsMockCreateOrderParamPtrs
	expectationOrigins LomsMockCreateOrderExpectationOrigins
	results            *LomsMockCreateOrderResults
	returnOrigin       string
	Counter            uint64
}

// LomsMockCreateOrderParams contains parameters of the Loms.CreateOrder
type LomsMockCreateOrderParams struct {
	ctx context.Context
	req *pbLoms.OrderCreateRequest
}

// LomsMockCreateOrderParamPtrs contains pointers to parameters of the Loms.CreateOrder
type LomsMockCreateOrderParamPtrs struct {
	ctx *context.Context
	req **pbLoms.OrderCreateRequest
}

// LomsMockCreateOrderResults contains results of the Loms.CreateOrder
type LomsMockCreateOrderResults struct {
	op1 *pbLoms.OrderCreateResponse
	err error
}

// LomsMockCreateOrderOrigins contains origins of expectations of the Loms.CreateOrder
type LomsMockCreateOrderExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateOrder *mLomsMockCreateOrder) Optional() *mLomsMockCreateOrder {
	mmCreateOrder.optional = true
	return mmCreateOrder
}

// Expect sets up expected params for Loms.CreateOrder
func (mmCreateOrder *mLomsMockCreateOrder) Expect(ctx context.Context, req *pbLoms.OrderCreateRequest) *mLomsMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsMockCreateOrderExpectation{}
	}

	if mmCreateOrder.defaultExpectation.paramPtrs != nil {
		mmCreateOrder.mock.t.Fatalf("LomsMock.CreateOrder mock is already set by ExpectParams functions")
	}

	mmCreateOrder.defaultExpectation.params = &LomsMockCreateOrderParams{ctx, req}
	mmCreateOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateOrder.expectations {
		if minimock.Equal(e.params, mmCreateOrder.defaultExpectation.params) {
			mmCreateOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateOrder.defaultExpectation.params)
		}
	}

	return mmCreateOrder
}

// ExpectCtxParam1 sets up expected param ctx for Loms.CreateOrder
func (mmCreateOrder *mLomsMockCreateOrder) ExpectCtxParam1(ctx context.Context) *mLomsMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsMockCreateOrderExpectation{}
	}

	if mmCreateOrder.defaultExpectation.params != nil {
		mmCreateOrder.mock.t.Fatalf("LomsMock.CreateOrder mock is already set by Expect")
	}

	if mmCreateOrder.defaultExpectation.paramPtrs == nil {
		mmCreateOrder.defaultExpectation.paramPtrs = &LomsMockCreateOrderParamPtrs{}
	}
	mmCreateOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateOrder
}

// ExpectReqParam2 sets up expected param req for Loms.CreateOrder
func (mmCreateOrder *mLomsMockCreateOrder) ExpectReqParam2(req *pbLoms.OrderCreateRequest) *mLomsMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsMockCreateOrderExpectation{}
	}

	if mmCreateOrder.defaultExpectation.params != nil {
		mmCreateOrder.mock.t.Fatalf("LomsMock.CreateOrder mock is already set by Expect")
	}

	if mmCreateOrder.defaultExpectation.paramPtrs == nil {
		mmCreateOrder.defaultExpectation.paramPtrs = &LomsMockCreateOrderParamPtrs{}
	}
	mmCreateOrder.defaultExpectation.paramPtrs.req = &req
	mmCreateOrder.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmCreateOrder
}

// Inspect accepts an inspector function that has same arguments as the Loms.CreateOrder
func (mmCreateOrder *mLomsMockCreateOrder) Inspect(f func(ctx context.Context, req *pbLoms.OrderCreateRequest)) *mLomsMockCreateOrder {
	if mmCreateOrder.mock.inspectFuncCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("Inspect function is already set for LomsMock.CreateOrder")
	}

	mmCreateOrder.mock.inspectFuncCreateOrder = f

	return mmCreateOrder
}

// Return sets up results that will be returned by Loms.CreateOrder
func (mmCreateOrder *mLomsMockCreateOrder) Return(op1 *pbLoms.OrderCreateResponse, err error) *LomsMock {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsMockCreateOrderExpectation{mock: mmCreateOrder.mock}
	}
	mmCreateOrder.defaultExpectation.results = &LomsMockCreateOrderResults{op1, err}
	mmCreateOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateOrder.mock
}

// Set uses given function f to mock the Loms.CreateOrder method
func (mmCreateOrder *mLomsMockCreateOrder) Set(f func(ctx context.Context, req *pbLoms.OrderCreateRequest) (op1 *pbLoms.OrderCreateResponse, err error)) *LomsMock {
	if mmCreateOrder.defaultExpectation != nil {
		mmCreateOrder.mock.t.Fatalf("Default expectation is already set for the Loms.CreateOrder method")
	}

	if len(mmCreateOrder.expectations) > 0 {
		mmCreateOrder.mock.t.Fatalf("Some expectations are already set for the Loms.CreateOrder method")
	}

	mmCreateOrder.mock.funcCreateOrder = f
	mmCreateOrder.mock.funcCreateOrderOrigin = minimock.CallerInfo(1)
	return mmCreateOrder.mock
}

// When sets expectation for the Loms.CreateOrder which will trigger the result defined by the following
// Then helper
func (mmCreateOrder *mLomsMockCreateOrder) When(ctx context.Context, req *pbLoms.OrderCreateRequest) *LomsMockCreateOrderExpectation {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsMock.CreateOrder mock is already set by Set")
	}

	expectation := &LomsMockCreateOrderExpectation{
		mock:               mmCreateOrder.mock,
		params:             &LomsMockCreateOrderParams{ctx, req},
		expectationOrigins: LomsMockCreateOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateOrder.expectations = append(mmCreateOrder.expectations, expectation)
	return expectation
}

// Then sets up Loms.CreateOrder return parameters for the expectation previously defined by the When method
func (e *LomsMockCreateOrderExpectation) Then(op1 *pbLoms.OrderCreateResponse, err error) *LomsMock {
	e.results = &LomsMockCreateOrderResults{op1, err}
	return e.mock
}

// Times sets number of times Loms.CreateOrder should be invoked
func (mmCreateOrder *mLomsMockCreateOrder) Times(n uint64) *mLomsMockCreateOrder {
	if n == 0 {
		mmCreateOrder.mock.t.Fatalf("Times of LomsMock.CreateOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateOrder.expectedInvocations, n)
	mmCreateOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateOrder
}

func (mmCreateOrder *mLomsMockCreateOrder) invocationsDone() bool {
	if len(mmCreateOrder.expectations) == 0 && mmCreateOrder.defaultExpectation == nil && mmCreateOrder.mock.funcCreateOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateOrder.mock.afterCreateOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateOrder implements mm_service.Loms
func (mmCreateOrder *LomsMock) CreateOrder(ctx context.Context, req *pbLoms.OrderCreateRequest) (op1 *pbLoms.OrderCreateResponse, err error) {
	mm_atomic.AddUint64(&mmCreateOrder.beforeCreateOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateOrder.afterCreateOrderCounter, 1)

	mmCreateOrder.t.Helper()

	if mmCreateOrder.inspectFuncCreateOrder != nil {
		mmCreateOrder.inspectFuncCreateOrder(ctx, req)
	}

	mm_params := LomsMockCreateOrderParams{ctx, req}

	// Record call args
	mmCreateOrder.CreateOrderMock.mutex.Lock()
	mmCreateOrder.CreateOrderMock.callArgs = append(mmCreateOrder.CreateOrderMock.callArgs, &mm_params)
	mmCreateOrder.CreateOrderMock.mutex.Unlock()

	for _, e := range mmCreateOrder.CreateOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.op1, e.results.err
		}
	}

	if mmCreateOrder.CreateOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateOrder.CreateOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateOrder.CreateOrderMock.defaultExpectation.params
		mm_want_ptrs := mmCreateOrder.CreateOrderMock.defaultExpectation.paramPtrs

		mm_got := LomsMockCreateOrderParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateOrder.t.Errorf("LomsMock.CreateOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateOrder.CreateOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmCreateOrder.t.Errorf("LomsMock.CreateOrder got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateOrder.CreateOrderMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateOrder.t.Errorf("LomsMock.CreateOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateOrder.CreateOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateOrder.CreateOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateOrder.t.Fatal("No results are set for the LomsMock.CreateOrder")
		}
		return (*mm_results).op1, (*mm_results).err
	}
	if mmCreateOrder.funcCreateOrder != nil {
		return mmCreateOrder.funcCreateOrder(ctx, req)
	}
	mmCreateOrder.t.Fatalf("Unexpected call to LomsMock.CreateOrder. %v %v", ctx, req)
	return
}

// CreateOrderAfterCounter returns a count of finished LomsMock.CreateOrder invocations
func (mmCreateOrder *LomsMock) CreateOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.afterCreateOrderCounter)
}

// CreateOrderBeforeCounter returns a count of LomsMock.CreateOrder invocations
func (mmCreateOrder *LomsMock) CreateOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.beforeCreateOrderCounter)
}

// Calls returns a list of arguments used in each call to LomsMock.CreateOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateOrder *mLomsMockCreateOrder) Calls() []*LomsMockCreateOrderParams {
	mmCreateOrder.mutex.RLock()

	argCopy := make([]*LomsMockCreateOrderParams, len(mmCreateOrder.callArgs))
	copy(argCopy, mmCreateOrder.callArgs)

	mmCreateOrder.mutex.RUnlock()

	return argCopy
}

// MinimockCreateOrderDone returns true if the count of the CreateOrder invocations corresponds
// the number of defined expectations
func (m *LomsMock) MinimockCreateOrderDone() bool {
	if m.CreateOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateOrderMock.invocationsDone()
}

// MinimockCreateOrderInspect logs each unmet expectation
func (m *LomsMock) MinimockCreateOrderInspect() {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsMock.CreateOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateOrderCounter := mm_atomic.LoadUint64(&m.afterCreateOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && afterCreateOrderCounter < 1 {
		if m.CreateOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsMock.CreateOrder at\n%s", m.CreateOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsMock.CreateOrder at\n%s with params: %#v", m.CreateOrderMock.defaultExpectation.expectationOrigins.origin, *m.CreateOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && afterCreateOrderCounter < 1 {
		m.t.Errorf("Expected call to LomsMock.CreateOrder at\n%s", m.funcCreateOrderOrigin)
	}

	if !m.CreateOrderMock.invocationsDone() && afterCreateOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsMock.CreateOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateOrderMock.expectedInvocations), m.CreateOrderMock.expectedInvocationsOrigin, afterCreateOrderCounter)
	}
}

type mLomsMockGetStocksInfo struct {
	optional           bool
	mock               *LomsMock
	defaultExpectation *LomsMockGetStocksInfoExpectation
	expectations       []*LomsMockGetStocksInfoExpectation

	callArgs []*LomsMockGetStocksInfoParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsMockGetStocksInfoExpectation specifies expectation struct of the Loms.GetStocksInfo
type LomsMockGetStocksInfoExpectation struct {
	mock               *LomsMock
	params             *LomsMockGetStocksInfoParams
	paramPtrs          *LomsMockGetStocksInfoParamPtrs
	expectationOrigins LomsMockGetStocksInfoExpectationOrigins
	results            *LomsMockGetStocksInfoResults
	returnOrigin       string
	Counter            uint64
}

// LomsMockGetStocksInfoParams contains parameters of the Loms.GetStocksInfo
type LomsMockGetStocksInfoParams struct {
	ctx context.Context
	req *pbLoms.StocksInfoRequest
}

// LomsMockGetStocksInfoParamPtrs contains pointers to parameters of the Loms.GetStocksInfo
type LomsMockGetStocksInfoParamPtrs struct {
	ctx *context.Context
	req **pbLoms.StocksInfoRequest
}

// LomsMockGetStocksInfoResults contains results of the Loms.GetStocksInfo
type LomsMockGetStocksInfoResults struct {
	sp1 *pbLoms.StocksInfoResponse
	err error
}

// LomsMockGetStocksInfoOrigins contains origins of expectations of the Loms.GetStocksInfo
type LomsMockGetStocksInfoExpectationOrigins struct {
	origin    string
	originCtx string
	originReq string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetStocksInfo *mLomsMockGetStocksInfo) Optional() *mLomsMockGetStocksInfo {
	mmGetStocksInfo.optional = true
	return mmGetStocksInfo
}

// Expect sets up expected params for Loms.GetStocksInfo
func (mmGetStocksInfo *mLomsMockGetStocksInfo) Expect(ctx context.Context, req *pbLoms.StocksInfoRequest) *mLomsMockGetStocksInfo {
	if mmGetStocksInfo.mock.funcGetStocksInfo != nil {
		mmGetStocksInfo.mock.t.Fatalf("LomsMock.GetStocksInfo mock is already set by Set")
	}

	if mmGetStocksInfo.defaultExpectation == nil {
		mmGetStocksInfo.defaultExpectation = &LomsMockGetStocksInfoExpectation{}
	}

	if mmGetStocksInfo.defaultExpectation.paramPtrs != nil {
		mmGetStocksInfo.mock.t.Fatalf("LomsMock.GetStocksInfo mock is already set by ExpectParams functions")
	}

	mmGetStocksInfo.defaultExpectation.params = &LomsMockGetStocksInfoParams{ctx, req}
	mmGetStocksInfo.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetStocksInfo.expectations {
		if minimock.Equal(e.params, mmGetStocksInfo.defaultExpectation.params) {
			mmGetStocksInfo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetStocksInfo.defaultExpectation.params)
		}
	}

	return mmGetStocksInfo
}

// ExpectCtxParam1 sets up expected param ctx for Loms.GetStocksInfo
func (mmGetStocksInfo *mLomsMockGetStocksInfo) ExpectCtxParam1(ctx context.Context) *mLomsMockGetStocksInfo {
	if mmGetStocksInfo.mock.funcGetStocksInfo != nil {
		mmGetStocksInfo.mock.t.Fatalf("LomsMock.GetStocksInfo mock is already set by Set")
	}

	if mmGetStocksInfo.defaultExpectation == nil {
		mmGetStocksInfo.defaultExpectation = &LomsMockGetStocksInfoExpectation{}
	}

	if mmGetStocksInfo.defaultExpectation.params != nil {
		mmGetStocksInfo.mock.t.Fatalf("LomsMock.GetStocksInfo mock is already set by Expect")
	}

	if mmGetStocksInfo.defaultExpectation.paramPtrs == nil {
		mmGetStocksInfo.defaultExpectation.paramPtrs = &LomsMockGetStocksInfoParamPtrs{}
	}
	mmGetStocksInfo.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetStocksInfo.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetStocksInfo
}

// ExpectReqParam2 sets up expected param req for Loms.GetStocksInfo
func (mmGetStocksInfo *mLomsMockGetStocksInfo) ExpectReqParam2(req *pbLoms.StocksInfoRequest) *mLomsMockGetStocksInfo {
	if mmGetStocksInfo.mock.funcGetStocksInfo != nil {
		mmGetStocksInfo.mock.t.Fatalf("LomsMock.GetStocksInfo mock is already set by Set")
	}

	if mmGetStocksInfo.defaultExpectation == nil {
		mmGetStocksInfo.defaultExpectation = &LomsMockGetStocksInfoExpectation{}
	}

	if mmGetStocksInfo.defaultExpectation.params != nil {
		mmGetStocksInfo.mock.t.Fatalf("LomsMock.GetStocksInfo mock is already set by Expect")
	}

	if mmGetStocksInfo.defaultExpectation.paramPtrs == nil {
		mmGetStocksInfo.defaultExpectation.paramPtrs = &LomsMockGetStocksInfoParamPtrs{}
	}
	mmGetStocksInfo.defaultExpectation.paramPtrs.req = &req
	mmGetStocksInfo.defaultExpectation.expectationOrigins.originReq = minimock.CallerInfo(1)

	return mmGetStocksInfo
}

// Inspect accepts an inspector function that has same arguments as the Loms.GetStocksInfo
func (mmGetStocksInfo *mLomsMockGetStocksInfo) Inspect(f func(ctx context.Context, req *pbLoms.StocksInfoRequest)) *mLomsMockGetStocksInfo {
	if mmGetStocksInfo.mock.inspectFuncGetStocksInfo != nil {
		mmGetStocksInfo.mock.t.Fatalf("Inspect function is already set for LomsMock.GetStocksInfo")
	}

	mmGetStocksInfo.mock.inspectFuncGetStocksInfo = f

	return mmGetStocksInfo
}

// Return sets up results that will be returned by Loms.GetStocksInfo
func (mmGetStocksInfo *mLomsMockGetStocksInfo) Return(sp1 *pbLoms.StocksInfoResponse, err error) *LomsMock {
	if mmGetStocksInfo.mock.funcGetStocksInfo != nil {
		mmGetStocksInfo.mock.t.Fatalf("LomsMock.GetStocksInfo mock is already set by Set")
	}

	if mmGetStocksInfo.defaultExpectation == nil {
		mmGetStocksInfo.defaultExpectation = &LomsMockGetStocksInfoExpectation{mock: mmGetStocksInfo.mock}
	}
	mmGetStocksInfo.defaultExpectation.results = &LomsMockGetStocksInfoResults{sp1, err}
	mmGetStocksInfo.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetStocksInfo.mock
}

// Set uses given function f to mock the Loms.GetStocksInfo method
func (mmGetStocksInfo *mLomsMockGetStocksInfo) Set(f func(ctx context.Context, req *pbLoms.StocksInfoRequest) (sp1 *pbLoms.StocksInfoResponse, err error)) *LomsMock {
	if mmGetStocksInfo.defaultExpectation != nil {
		mmGetStocksInfo.mock.t.Fatalf("Default expectation is already set for the Loms.GetStocksInfo method")
	}

	if len(mmGetStocksInfo.expectations) > 0 {
		mmGetStocksInfo.mock.t.Fatalf("Some expectations are already set for the Loms.GetStocksInfo method")
	}

	mmGetStocksInfo.mock.funcGetStocksInfo = f
	mmGetStocksInfo.mock.funcGetStocksInfoOrigin = minimock.CallerInfo(1)
	return mmGetStocksInfo.mock
}

// When sets expectation for the Loms.GetStocksInfo which will trigger the result defined by the following
// Then helper
func (mmGetStocksInfo *mLomsMockGetStocksInfo) When(ctx context.Context, req *pbLoms.StocksInfoRequest) *LomsMockGetStocksInfoExpectation {
	if mmGetStocksInfo.mock.funcGetStocksInfo != nil {
		mmGetStocksInfo.mock.t.Fatalf("LomsMock.GetStocksInfo mock is already set by Set")
	}

	expectation := &LomsMockGetStocksInfoExpectation{
		mock:               mmGetStocksInfo.mock,
		params:             &LomsMockGetStocksInfoParams{ctx, req},
		expectationOrigins: LomsMockGetStocksInfoExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetStocksInfo.expectations = append(mmGetStocksInfo.expectations, expectation)
	return expectation
}

// Then sets up Loms.GetStocksInfo return parameters for the expectation previously defined by the When method
func (e *LomsMockGetStocksInfoExpectation) Then(sp1 *pbLoms.StocksInfoResponse, err error) *LomsMock {
	e.results = &LomsMockGetStocksInfoResults{sp1, err}
	return e.mock
}

// Times sets number of times Loms.GetStocksInfo should be invoked
func (mmGetStocksInfo *mLomsMockGetStocksInfo) Times(n uint64) *mLomsMockGetStocksInfo {
	if n == 0 {
		mmGetStocksInfo.mock.t.Fatalf("Times of LomsMock.GetStocksInfo mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetStocksInfo.expectedInvocations, n)
	mmGetStocksInfo.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetStocksInfo
}

func (mmGetStocksInfo *mLomsMockGetStocksInfo) invocationsDone() bool {
	if len(mmGetStocksInfo.expectations) == 0 && mmGetStocksInfo.defaultExpectation == nil && mmGetStocksInfo.mock.funcGetStocksInfo == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetStocksInfo.mock.afterGetStocksInfoCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetStocksInfo.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetStocksInfo implements mm_service.Loms
func (mmGetStocksInfo *LomsMock) GetStocksInfo(ctx context.Context, req *pbLoms.StocksInfoRequest) (sp1 *pbLoms.StocksInfoResponse, err error) {
	mm_atomic.AddUint64(&mmGetStocksInfo.beforeGetStocksInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmGetStocksInfo.afterGetStocksInfoCounter, 1)

	mmGetStocksInfo.t.Helper()

	if mmGetStocksInfo.inspectFuncGetStocksInfo != nil {
		mmGetStocksInfo.inspectFuncGetStocksInfo(ctx, req)
	}

	mm_params := LomsMockGetStocksInfoParams{ctx, req}

	// Record call args
	mmGetStocksInfo.GetStocksInfoMock.mutex.Lock()
	mmGetStocksInfo.GetStocksInfoMock.callArgs = append(mmGetStocksInfo.GetStocksInfoMock.callArgs, &mm_params)
	mmGetStocksInfo.GetStocksInfoMock.mutex.Unlock()

	for _, e := range mmGetStocksInfo.GetStocksInfoMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmGetStocksInfo.GetStocksInfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetStocksInfo.GetStocksInfoMock.defaultExpectation.Counter, 1)
		mm_want := mmGetStocksInfo.GetStocksInfoMock.defaultExpectation.params
		mm_want_ptrs := mmGetStocksInfo.GetStocksInfoMock.defaultExpectation.paramPtrs

		mm_got := LomsMockGetStocksInfoParams{ctx, req}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetStocksInfo.t.Errorf("LomsMock.GetStocksInfo got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetStocksInfo.GetStocksInfoMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.req != nil && !minimock.Equal(*mm_want_ptrs.req, mm_got.req) {
				mmGetStocksInfo.t.Errorf("LomsMock.GetStocksInfo got unexpected parameter req, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetStocksInfo.GetStocksInfoMock.defaultExpectation.expectationOrigins.originReq, *mm_want_ptrs.req, mm_got.req, minimock.Diff(*mm_want_ptrs.req, mm_got.req))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetStocksInfo.t.Errorf("LomsMock.GetStocksInfo got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetStocksInfo.GetStocksInfoMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetStocksInfo.GetStocksInfoMock.defaultExpectation.results
		if mm_results == nil {
			mmGetStocksInfo.t.Fatal("No results are set for the LomsMock.GetStocksInfo")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmGetStocksInfo.funcGetStocksInfo != nil {
		return mmGetStocksInfo.funcGetStocksInfo(ctx, req)
	}
	mmGetStocksInfo.t.Fatalf("Unexpected call to LomsMock.GetStocksInfo. %v %v", ctx, req)
	return
}

// GetStocksInfoAfterCounter returns a count of finished LomsMock.GetStocksInfo invocations
func (mmGetStocksInfo *LomsMock) GetStocksInfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStocksInfo.afterGetStocksInfoCounter)
}

// GetStocksInfoBeforeCounter returns a count of LomsMock.GetStocksInfo invocations
func (mmGetStocksInfo *LomsMock) GetStocksInfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStocksInfo.beforeGetStocksInfoCounter)
}

// Calls returns a list of arguments used in each call to LomsMock.GetStocksInfo.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetStocksInfo *mLomsMockGetStocksInfo) Calls() []*LomsMockGetStocksInfoParams {
	mmGetStocksInfo.mutex.RLock()

	argCopy := make([]*LomsMockGetStocksInfoParams, len(mmGetStocksInfo.callArgs))
	copy(argCopy, mmGetStocksInfo.callArgs)

	mmGetStocksInfo.mutex.RUnlock()

	return argCopy
}

// MinimockGetStocksInfoDone returns true if the count of the GetStocksInfo invocations corresponds
// the number of defined expectations
func (m *LomsMock) MinimockGetStocksInfoDone() bool {
	if m.GetStocksInfoMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetStocksInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetStocksInfoMock.invocationsDone()
}

// MinimockGetStocksInfoInspect logs each unmet expectation
func (m *LomsMock) MinimockGetStocksInfoInspect() {
	for _, e := range m.GetStocksInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsMock.GetStocksInfo at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetStocksInfoCounter := mm_atomic.LoadUint64(&m.afterGetStocksInfoCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetStocksInfoMock.defaultExpectation != nil && afterGetStocksInfoCounter < 1 {
		if m.GetStocksInfoMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsMock.GetStocksInfo at\n%s", m.GetStocksInfoMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsMock.GetStocksInfo at\n%s with params: %#v", m.GetStocksInfoMock.defaultExpectation.expectationOrigins.origin, *m.GetStocksInfoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetStocksInfo != nil && afterGetStocksInfoCounter < 1 {
		m.t.Errorf("Expected call to LomsMock.GetStocksInfo at\n%s", m.funcGetStocksInfoOrigin)
	}

	if !m.GetStocksInfoMock.invocationsDone() && afterGetStocksInfoCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsMock.GetStocksInfo at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetStocksInfoMock.expectedInvocations), m.GetStocksInfoMock.expectedInvocationsOrigin, afterGetStocksInfoCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LomsMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateOrderInspect()

			m.MinimockGetStocksInfoInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LomsMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LomsMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateOrderDone() &&
		m.MinimockGetStocksInfoDone()
}
