// Package model ...
package model

import "errors"

// Default ...
var (
	// ErrDefault ...
	ErrDefault = errors.New("проблемы из-за неисправностей в системе")
	// ErrUserIDMoreThanZero ...
	ErrUserIDMoreThanZero = errors.New("идентификатор пользователя должен быть натуральным числом (больше нуля)")
	// ErrListItemsEmpty
	ErrListItemsEmpty = errors.New("список товаров не должен быть пустым")
	//ErrSkuMoreThanZero ...
	ErrSkuMoreThanZero = errors.New("идентификатор товара должен быть натуральным числом (больше нуля)")
	//ErrCountMoreThanZero ...
	ErrCountMoreThanZero = errors.New("сount должен быть натуральным числом (больше нуля)")
)

// Order ...
var (
	// ErrOrderIDMoreThanZero ...
	ErrOrderIDMoreThanZero = errors.New("идентификатор заказа должен быть натуральным числом (больше нуля)")
	// ErrOrderIDNotFound ...
	ErrOrderIDNotFound = errors.New("можно получить информацию только для существующего в системе заказа")
	// ErrOrderPayNotFound ...
	ErrOrderPayNotFound = errors.New("можно оплачивать только существующий заказ")
	// ErrOrderAlreadyPay ...
	ErrOrderAlreadyPay = errors.New("оплата оплаченного заказа разрешается")
	// ErrOrderStatusNotAwaitingPayment
	ErrOrderStatusNotAwaitingPayment = errors.New("оплата заказа в невалидном статусе невозможна")
	// ErrOrderCancelNotFound ...
	ErrOrderCancelNotFound = errors.New("можно отменять только существующий заказ")
	// ErrOrderAlreadyCanceled ...
	ErrOrderAlreadyCanceled = errors.New("отмена отмененного заказа разрешается (идемпотентность)")
	// ErrOrderStatusFailedOrPaid
	ErrOrderStatusFailedOrPaid = errors.New("невозможность отменить неудавшийся заказ, а также оплаченный")
)

// Stocks ...
var (
	// ErrNoStockForReserve ...
	ErrNoStockForReserve = errors.New("для всех товаров сток должен быть больше или равен запрашиваемому")
	//ErrStockInfoNotFound ...
	ErrStockInfoNotFound = errors.New("невозможно создать заказ, если по хотя бы одному товару нет информации о стоках")
	// ErrStockSkuNotFound ...
	ErrStockSkuNotFound = errors.New("можно получить информацию по стокам, если она есть в хранилище")
)
