// Package model ...
package model

// OrderStorage ...
type OrderStorage = map[int64]OrderInfo

// OrderInfo ...
type OrderInfo struct {
	UserID int64
	Status string
	Items  []Item
}

var (
	// StatusOrderNew ...
	StatusOrderNew = "new"
	// StatusOrderAwaitingPayment ...
	StatusOrderAwaitingPayment = "awaiting payment"
	// StatusOrderFailed ...
	StatusOrderFailed = "failed"
	// StatusOrderPaid ...
	StatusOrderPaid = "paid"
	// StatusOrderCancelled ...
	StatusOrderCancelled = "cancelled"
	// ErrorOrderID ...
	ErrorOrderID int64 = -1
)

var (
	// RequestStock ...
	RequestStock = "stock"
	// RequestOrder ...
	RequestOrder = "order"
)
